name: Sync SVG to Cloudflare R2

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Specify a release tag manually if known."
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      - name: Determine Release Tag
        id: determine-tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "Tag from release event: ${{ github.event.release.tag_name }}"
            echo "::set-output name=release_tag::${{ github.event.release.tag_name }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manually specified tag: ${{ github.event.inputs.tag }}"
            echo "::set-output name=release_tag::${{ github.event.inputs.tag }}"
          else
            echo "No valid event type for release tagging."
            exit 1
          fi

      - name: Sync SVG to Cloudflare R2
        env:
          CLOUDFLARE_R2_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
          CLOUDFLARE_R2_SECRET_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
          CLOUDFLARE_R2_ENDPOINT: https://06898acc14d0b9633f259fe20145fd49.r2.cloudflarestorage.com
          AWS_REGION: us-east-1
        run: |
          RELEASE_TAG=${{ steps.determine-tag.outputs.release_tag }}
          echo "Using Release Tag: $RELEASE_TAG"
          aws configure set aws_access_key_id ${CLOUDFLARE_R2_ACCESS_KEY}
          aws configure set aws_secret_access_key ${CLOUDFLARE_R2_SECRET_KEY}
          aws configure set region ${AWS_REGION}
          aws s3 sync ./MoeLite/svgs s3://moe-icons-website/version-$RELEASE_TAG/ \
          --endpoint-url ${CLOUDFLARE_R2_ENDPOINT} --debug
