name: Sync SVG to Cloudflare R2

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出当前仓库代码
      - name: Checkout repo
        uses: actions/checkout@v2

      # 安装 AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      # 使用 aws-cli 将 SVG 文件同步到 Cloudflare R2
      - name: Sync SVG to Cloudflare R2
        env:
          CLOUDFLARE_R2_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
          CLOUDFLARE_R2_SECRET_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
        run: |
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          aws configure set aws_access_key_id ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
          aws s3 sync ./MoeLite/svgs s3://moe-icons-website/version-${{ github.event.release.tag_name }}/ \
          --endpoint-url https://06898acc14d0b9633f259fe20145fd49.r2.cloudflarestorage.com --debug
